### ISSUE TITLE
Server icon sidebar misaligned after recent BDFDB update to v1.9.6

### ISSUE THREAD

**Issue by biru-cs** [DiscordStyles/Slate#78] opened 2021-11-02 15:42 UTC
**Describe the bug**  
Server icon sidebar is off-center now after the recent BDFDB update to version 1.9.6.

**To Reproduce**  
Updated to BDFDB v1.9.6, there is nothing more I could see.

**Screenshots**  
![image](https://user-images.githubusercontent.com/81181874/139880039-bfe6894c-424b-4911-a56c-d51c3994d5ef.png)

**Infomation**  
Discord channel: Stable  
OS: Windows 10  
Mod: BetterDiscord  
Discord language: US English

**Comment by Gibbu** [comment] 2021-11-02 22:19
This has nothing to do with BDFDB. It was a Discord update which has been fixed.

Do the following:
1. Re-enable the theme.
2. Restart your Discord.
3. Disable Cache.
    \> Press `CTRL` + `SHIFT` + `i`.
    \> Go to the "Network" tab.
    \> Check "Disable Cache".
    \> Reload Discord.
    \> Repeat steps, uncheck "Disable Chache".

**Comment by biru-cs** [comment] 2021-11-03 12:58
Can confirm. BDFDB has been updated to v1.9.7 and the theme is back to normal now. Discord itself probably updated automatically as well.

Thank you for your time!

**Comment by mochaaP** [comment] 2021-11-04 09:45
duplicate of #77

**Closed** 2021-11-04 11:21 UTC
Labels: bug
